# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9f826400eede8ea2bde4bc9e2b51c849306fc4f6eaaa6e836c1f7a78dd2a71a2d680e010614c4f01ad514ecc2e7d440bf06b36ad74df22e5a48df9e6bea573d2

test:
  secret_key_base: 449a81b9607cc6b44810f588c4cb08ab17454a300c3082a990e715e39b4d65bd36db0f8285a9800e6c83891901c07a34b00259c30a2d7fa4199f454048420d39

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
